---
title: |
  Economic concerns appear to be weak causal predictors of White political identity
short-title: Economic concerns
published: "Manuscript draft: please do not share without author permission."
code-repo: "For replication, go to: <https:://github.com/DamonCharlesRoberts/white-identity-sources>."
author:
  - name: Damon C. Roberts
    email: damon.roberts-1@colorado.edu
    orcid: 0000-0002-4360-3675
    title: PhD Candidate
    affiliations:
      - id: CU
        name: University of Colorado Boulder
        department: Political Science
        address: 333 UCB
        city: Boulder
        region: CO 
        postal-code: 80309-0333
abstract: |
    Does economic or social and political threat explain white identity? Two leading arguments suggest that White identity results from a disruption of the racial status quo. However, they disagree on which disrupted element drives it. While one suggests that White identity comes from discriminatory attitudes, the other suggests that it is the result of concern with increased economic competition between Whites and other racial groups. Using data from the American National Election Study that measure egotropic and sociotropic economic attitudes and leveraging questions gauging attitudes about social and political changes of influence from the 2012, 2016, and 2020 American National Election Studies, this manuscript takes advantage of penalized regression for variable selection. On balance, the models suggest that the hypothesis of economic competition is weaker than some suggest. I take this as evidence that White political identity is largely the result of Whites' concerns with protecting the social and political status quo - and not so much economic.
thanks: |
    I would like to thank Jennifer Wolak for her feedback on the many drafts of this manuscript. I would also like to thank the Keller Center for the First Amendment for the research appointment that gave me the space to work on the early stages of this project. I would also like to thank Anand Sokhey and John Griffin for their advice and suggestions in the early drafts of this paper. I would also like to thank Tabitha Bonilla, Nicole Yadon, and participants and audience members of a Midwestern Political Science Association panel for which an earlier draft this idea was presented. I would also like to thank Tamar Malloy, Andrew Philips, Kathryn Schauer, Rachel O'Neal, Alexander Jensen, and Komal Kauer for their encouragement and feedback at various stages of this project's development. All errors contained in this manuscript are ultimately mine.
additional-info: |
  I have no known conflict of interest to disclose.
keywords:
  - white identity
  - economic threat
  - cultural threat
date: today
bibliography: "../assets/wid.bib"
format:
  hikmah-pdf: 
    biblatex-chicago: true
    biblio-style: authordate
    biblatexoptions:
      - backend=biber
      - autolang=hyphen
      - isbn=false
      - uniquename=false
linestretch: 2
execute:
  echo: false
  warning: false
  message: false
---

```{r}
#| label: block-setup

# set seed
set.seed(90210)

# source cleaning scripts
source('../code/dcr_anes_2012_cleaning.R')
source('../code/dcr_anes_2016_cleaning.R')
source('../code/dcr_anes_2020_cleaning.R')

# modularly load functions
box::use(
    dplyr = dplyr[select, filter, mutate, case_when, rename],
    tidyr = tidyr[drop_na],
    mice = mice[mice, pool],
    miceadds = miceadds[mids2datlist],
    brms = brms[brm, brm_multiple, set_prior, lasso, cumulative, prior],
    tibble = tibble[tribble],
    modelsummary = modelsummary[datasummary_skim, modelsummary],
    parameters = parameters[parameters, standardize_names],
    ggplot2 = ggplot2[ggplot, aes, position_dodge, theme_minimal, geom_vline, labs, theme, element_text, ggsave],
    tidybayes = tidybayes[geom_pointinterval]
)

# create list object for datasets
data = list()

# load the cleaned data
    #* 2012
data[['anes_2012']] = read.csv('../data/anes-2012/anes-2012-updated.csv') |>
    select(wid, female, rboff, epast, unpast, pid, edu, losejob, immtakejobs, raceResent, ecfamily, tradbreak, govbias, inflwhite, whitediscrim)
    #* 2016
data[['anes_2016']] = read.csv('../data/anes-2016/anes-2016-updated.csv') |>
    select(wid, female, rboff, epast, unpast, pid, edu, losejob, immtakejobs, raceResent, ecfamily, tradbreak, govbias, inflwhite, whitediscrim)
    #* 2020
data[['anes_2020']] = read.csv('../data/anes-2020/anes-2020-updated.csv') |>
    select(wid, female, rboff, epast, unpast, pid, edu, losejob, immtakejobs, raceResent, ecfamily, govbias, inflwhite, whitediscrim)
```

# Introduction

Those conducting post-mortem analyses of the 2016 Presidential election of Donald J. Trump, a presidential candidate that personifies White grievance politics, contend that the stronger than expected presence of non-college educated Whites explains his electoral success [@griffin_et-al_2017]. Analyses by political scientists largely contribute to Trump's success in attracting voters who see their Whiteness as a politically relevant identity where they are distinct from Americans of other racial groups [@jardina_2020_pp]. For a long time, political scientists saw White political behavior and attitudes through the lens of prejudice. These analyses exclude another dimension of Whites' racial attitudes: their affinity for, feelings of linked fate with other Whites and an expression that their race is a politically-relevant identity. More recently, scholars using the @tajfel_turner_1986 social psychological framework of identity challenge this tendency to focus on Whites' prejudice by arguing that some Whites may see their race as an identity essential and relevant to politics. As a result, while some may express out-group attitudes, they also express an in-group preference for other Whites [@jardina_2019_cup]. Despite the importance of these attitudes, the source of these in-group preferences remains somewhat unclear. 

There appears to be a mismatch between those who study sources of a variety of social identities and those that study White political identity. Scholars studying identity more broadly often focus on economic threats as a key motivator for an expressed connection to a social in-group [see @huddy_2001], however some scholars studying White political attitudes and racial identity tend to focus on the role of cultural and political threats [see @bartels_2020]. This mismatch leads to some to conceptualizing White identity as originating from economic views, in the tradition of the identity literature, while others conceptualize white identity as coming from political and cultural threat. 

I agree with those who focus on the connection between White political identity and cultural and political threats. I argue that White identifiers are concerned about their status in politics and society. Though, I acknowledge that economic threat is a potent activation of identity and encourages engagement of group-based behavior, White identity holds unique cultural and institutional significance in the U.S. [@rile-hayward_2013]. Concerns about economic standing is not entirely new to Whites (e.g., the Great Depression, the 2008 Housing Market Crash) and is likely more nebulous as to whether it disproportionately effects Whites. As political and societal power are shifting away from Whites, I suspect that this reflects a change to the racial hierarchy that is new to Whites and this may be driving the high levels of White political identification that many scholars report.

I examine the correlates of white identity. Using data from the 2012, 2016, and 2020 American National Election Study, I utilize penalized regression to test the claim that a handful of predictors that reflect attitudes about cultural and political power are more influential than general (sociotropic) and pocketbook (egotropic) attitudes about the economy. In each year, I find that cultural and political predictors are consistently stronger than economic attitudes. I close by arguing that scholars should continue to examine the mechanisms that explains this connection.

<!-- 
TODO: 
  - I've set up the puzzle, now explain where the literature is at
    - DONE
  - explain how the relative deprivation argument is better covered in the identity literature
    - DONE
  - make a strong assertion that I am testing against the relative deprivation argument and that I am in support of cultural explanations
  - explain what the next few sections of the paper do.
    - DONE
  - listen to the advice of Stimson and the Offspring
    - DONE
-->

<!--
The leading argument conceptualizes those expressing a positive White political identity as those motivated by group delineation and difference [@jardina2019] through cultural or other non-materialistic evaluations. Another interpretation of in-group affinity in the debate surrounding social identity theory sees in-group affinity as the result of relative deprivation or group competition [see @Huddy2012]; that is, a reaction to threats to material status. Those who argue for the latter illustrate this idea of group competition because non-college-educated Whites in 2016, who may be more susceptible to economic hardship and job market competition, were more supportive of Trump due to their concern about more staunch group competition. Many others disagree and argue that the 2016 electoral base for Trump was about prejudice and discrimination among Whites and that economic correlates are weak causal features [@fahey_et-al_2020].

To adjudicate between these two explanations of where White identity comes from in the post-Obama or "post-racial" era of American politics, I rely on the literature on social identity theory. This manuscript examines whether group conflict and feelings of relative material deprivation among Whites increase White identity. 

Given the growing body of literature on the implications of White political identity, I contend that the evidence points to measures that capture group differences and concern with social positioning as opposed to materially-based group competition or relative deprivation. There is ample evidence in the literature that many of the precursors for a politically relevant social identity among Whites are present. While group competition and relative deprivation may explain the motivation of some Whites to express in-group affinity, it is much farther from a complete explanation than proponents of it admit.

Using data from 2012, 2016, and 2020 American National Election Studies (ANES), I use common sociotropic (generalized attitudes of the economy, overall) and egotropic (more specific attitudes related to their personal financial situation) measures of an individual's attitudes towards the economy. I then put them in a penalized regression model along with several questions gauging White respondents' feelings of a loss in cultural and political influence. The model provides evidence supporting my expectations that non-material concerns are stronger causal predictors of White identity than economic indicators.
-->

# Identity and White political identity

<!--
TODO:
  - Start with evidence that demonstrates how economic threats activate identity politics, then discuss how people suggest that reactions to Trump are economic rather than racialized, then go into how others suggest that it is actually about cultural and political threat
-->

Social identity theory suggests that individuals form attitudes based on groups that they associate themselves with, even if those groups are subjectively defined [see @tajfel_turner_1986]. In the famous Robber's Cave experiment, @sherif_1988 divided a group of adolescent boys into two groups arbitrarily. After a week of spending time with others in the group, the boys had already provided labels that defined the two groups and distinguished themselves; one group called themselves the Eagles and the other group referred to themselves as the Rattlers. With the introduction of competition, these boys reported fierce levels of hostility toward the members of the other group and expressed positive attitudes toward those within the group. 

This example illustrates a number of features of social identities. The first feature of social identity theory is that these groups that we may associate ourselves with are often subjectively defined [see @huddy_2001]. The second feature is that these subjective definitions of the group make distinctions between the two groups that come to matter to members of each group - there are those part of our group and there are those that are part of that other group. Many cognitive theories suggest that this occurs as a result of the tendency for humans to reduce cognitive load by grouping things together [@huddy_2001]. The third feature is that the introduction of competition between these groups shapes attitudes toward those within and without your group. The motivator is that for groups that have higher status often want to keep that status and individuals in the high status group are much more likely to support inequality to satisfy that motivation [@burns_kinder_2012;@morrison_et-al_2009]. Fourth, these attitudes are long lasting and can be strongly held. An additional feature of theories of social identitiy is that the degree to which one might identify with one group or another is fluid and that whether one identity that one might hold is active or if it is another often depends on the context and the identity's relevance to that context [@huddy_2012].

Racial groups in the US contain a number of these features. As a result,a burgeoning literature in political science that has made this connection takes the racial identity of Whites more seriously as one that informs their political attitudes [see @jardina_2019_cup]. Race in America is subjectively defined [see @rile-hayward_2013] and these definitions are deeply embeded and reinforced by our institutions [@lopez_2006]. Whiteness and one's willingness to identify with that group is important [@wong_cho_2005] as it reflects a desire for an association with the history and affordances that comes with being White [@mcdermott_samson_2005]. 

In many eras of American history, there are a number of instances where we have sought to reclassify who is White. During the antebellum period, Whiteness was no longer simply one's economic class but now it had become a reflection of a racial hierarchy that afforded some various rights and excluded others from enjoying the same rights (e.g., literacy tests). During this era, rather than conceptualizing Whites as land-owners from Caucasian descent, the definition of what was White shifted to include those who had long considered to be non-White Europeans such as the Irish. Changes to definitions of who is White placed race and not just class as a primary source of who is afforded some rights and who are not [@rile-hayward_2013]. 

Whites hold a number of strong political attitudes that are racialized by politicians. Whites' attitudes toward welfare programs are not all too distinct from their attitudes toward Black Americans [@gilens_1999]. A provided explanation is that social welfare policies are more unpopular among Whites when the media frames these policies as benefiting non-Whites [@winter_2008;@van-doorn_2015]. When attitudes toward non-Whites are explicitly cued by messages that remind individuals of the racial hierarchy, these attitudes toward Blacks are more entrenched [@lyle_2014; see also @wellman_et-al_2016]. Attitudes about healthcare were shaped by prominent conservatives who pitched that Barack Obama, the first Black president, supported the Affordable Care Act as a way to disproportionately help Black Americans [@tesler_2012;@tesler_2016], that there was a rise of survey reports expressing old fashioned racism among Whites during his administration [@tesler_2013]. While Whites tend to report negative views about government aid for those in need when they are non-White recipients, evidence suggests that Whites who live in communities with a large porportion of the poor being White report much more positive views of the poor than those that view the poor as largely represented by non-Whites [@hopkins_2009] and that telling Whites that other Whites are going to be the beneficiaries of an entitlement program increases their support for such a program [@wetts_willer_2018].

As an identity, a large portion of the literature views these attitudes as coming from the presence or focus on economic threats. Some studying White political identity find economic predictors as substantively and statistically significant [see @perez_et-al_2022_pp]. From non-experimental evidence, others make similar arguments about what predicts white political identity. @bunyasi_2019 provides evidence which suggests that Trump's messages highlighting increased job market competition that was harming Whites because of affirmative action was a successful strategy and helped build his base of support. After all, the identity literature, more broadly, often focuses on economic threats. Evolutionary psychologists often take the position that identity and the resulting attitudes and behaviors directed toward out-groups is the result of competition over material resources [see @huddy_2001]. Among political scientists, many use this as an explanation for negative attitudes directed toward immigrants among those who feel insecure about their job prospects [@pardos-prado_xena_2019].

Not all agree, however. Some suggest that the negative attitudes that Whites express toward immigrants are a result of concerns about cultural changes to those that live in border towns [@hainmueller_hopkins_2014]. Others suggest that simply reminding Whites of these demographic shifts lead to an activation of these racial identity-based attitudes [@craig_richeson_2014]. Some other evidence suggests that these identity-based attitudes are better predicted by ethnic antagonism [@bartels_2020] and by racial animus [@fahey_et-al_2020] and explicitly take the position that these are not driven by a reaction to economic threats. However, these attitudes tend to focus on prejudiced views rather than a reflection of a connection to other whites. 

# Is white identity non-material?

As much of the literature on Whites' racial attitudes rely heavily on social identity theory as a paradigm, a significant portion of it presents the source of these group-based views as responses to economic threat. However, some disagree with such a position and view these attitudes as the result of changes to the racial hierarchy. Other perspectives provide explanations for Whites' attitudes and conceptualize the definition of Whiteness and White identity as a desire for retaining political power.

Historical accounts that contextualize attitudes stemming from White racial identity seem to suggest that, though economics is very embedded with racial attitudes, what it meant to be White was no longer about class but it became about what it meant for access to and privileges afforded by institutions [@rile-hayward_2013]. In the 19th century privilege came from one's freedom and from their wealth. For those who were not enslaved but were poor, they were not considered White and were than Whites who owned land [@rile-hayward_2013]. With the abolition of slavery, the concern became not about wealth but now about race. This motivated a shift in how the institutions and how Whites defined themselves. It became the focus for Whites to be a higher status group, regardless of whether or not they were poorer than formerly enslaved Black Americans [@rile-hayward_2013]. 

Many conceptualizations of White political identity align with its primary source as concern for the group's political power. While a key component of identity is a feeling of your fate as linked with others in your group [@leach_et-al_2008], this linked fate is conceptualized as the connection between attitudes and material forms of threat but that identity, in and of itself, is better conceptualized as a result of cultural or ideational threat [@donnelly_2020]. Aligning with the contextual account of racial identity for Whites, many conceptualize White identity as an expressed desire for a recognition of privilege and status by insitutions [@lopez_2006] and a connection with the history that connects Whites to their status [@mcdermott_samson_2005]. The prominent account of White political identity and its implications in contemporary American politics argues for a strong connection between White political identity and a desire to protect this racial hiearchy and status which reflects the tendency to report in-group oriented, and not necessarily out-group oriented, attitudes [@jardina_2019_cup].

As this is an open question and is rather a complex one, I attempt to first wade into this by parsing through which of these two perspectives are more plausible. As I discuss in the concluding section, I argue that scholars should continue to take the conceptualization and measurement of White political identification seriously and examine the particular mechanisms that connect economic and political threat to White political identity. In the next section, I examine whether attitudes expressing concern with economic threats or political, or broader societal, threats are stronger predictors of the degree to which someone feels that being White is important to their identity. The goal is not to test particular causal mechanisms but to examine whether my belief and other's that White identity reflects reactions to political threat moreso than it does economic.

<!-- 
TODO:
    - Then move into making my argument. We've got two competing views - the one that is popular in the identity lit, and then the one that suggests that it could be cultural or political threat. Then argue that what it really is that whites have not experienced cultural/political threats to the racial hierarchy and explain how historically that has been responded to.
      - DONE
-->

# Data

To examine whether Whites' attitudes expressing concern about political threats are stronger than their perceptions of the economy, I use 2012, 2016, and 2020 American National Election Studies (ANES). The studies are nationally representtaive questions that capture several questions that lend themselves to testing the relationship between economic and political concerns while also asking White respondents to report how important being White is to their identity.

Each study asks White respondents "How important is being White to your Identity" and offers them a five-point Likert scale with the options reflecting level of agreement with the question ^[Details about question wording, original ANES coding, and my coding for all variables I include in my models are included in @tbl-anes-measures]. They do not ask White respondents to report on measure items that are included in the White political identity measures of @jardina_2019_cup or the more complex battery of items that @helms_carter_1990 discuss. However, this question does reflect the conceptualization of White identity that reflects the degree to which one sees their Whiteness as part of who they are and reflects the conceptualization that others have used [see @schildkraut_2017;@perez_et-al_2022_pp]. 

The ANES does not ask questions that explicitly capture the attitudes of respondents about perceptions of the economy for different groups. Those that have lower incomes are more likely to feel insecurity about their financial status and are more likely to use this economic threat as a motivation for their negative attitudes toward immigrants [@pardos-prado_xena_2019]. Therefore, one measure of economic threat that I use is the respondent's reported level of family income. Those who hold lower levels of education are also likely to feel similar levels of insecurity about their economic status. Whites who report that they feel that their family is doing worse or will be doing worse also reflects a degree of insecurity about their economic status and may reflect perceptions of economic threat [@jardina_2019_cup]. I additionally include an item reflecting respondent's perceptions of economic mobility today relative to in the past. I additionally include questions about retrospective sociotropic evaluations of the economy. In 2012, Whites harboring negative attitudes of Obama rooted in racial animous were more likely to express more negative views of the economy relative to how it had been in the past [@sides_et-al_2018]. 

The ANES includes a number of questions that reflect perceptions of Whites losing political power. First I include a question that asks respondents to report whether or not they felt that Whites currently have too little or too much influence on politics today. I also want to examine the degree to which respondents feel that the institutions benefit non-Whites rather than whites by including a question that Whites face discrimmination and that the government is biased against Whites. I additionally include a question asking respondents about their belief that traditions in this country are breaking^[The ANES only include this question in the 2012 and 2016 questionaire]. 

Furthermore, the ANES includes the racial resentment battery which asks a series of questions that reflect Whites' beliefs that Blacks are individually responsible for their circumstances,  and that they are undeserving of any assistance. I control for racial resentment as the individual items likely confound the relationship between both economic and political threat measures on expressed White identity.

The summary of the literature points to a large number of potential predictors that influence the degree to which one takes on White political identity.  To adjudicate between hypotheses, there is value in a comprehensive model that considers the plausibility of each. Most models consider those predictors they believe are most plausible and do not include others that the researcher believes to be less plausible. They understandably do this out of concern with increases in the inefficiency of one's regression estimates the more predictors you include and therefore increases the risk of overfitting your model to your particular sample, thereby erroneously generalizing conclusions drawn from the model. Though this concern is reasonable, such a model necessarily neglects to examine the effects of the predictors a researcher believes to be less plausible.

Therefore, I elect to use a penalized regression model to balance between these concerns.  The literature surveyed above suggests that there are a small number of variables that do predict White political identity, and there are many others that have no effect. This implies that the L2 regularization parameter equals 0. This is because the L2 regularization parameter shrinks coefficients asymptotically toward zero. The L1 regularization parameter, however, does allow for a shrinkage parameter to pull coefficients to 0. Given this, it suggests that the more appropriate model to capture this debate would be the LASSO penalized regression.

One option for implementation is to use the ``classical" LASSO, which relies on an optimization procedure through cross-validation. It is a frequentist approach to LASSO penalized regression. However, there are several positive benefits to the second implementation of the LASSO penalized regression in a Bayesian framework [see @van-erp_et-al_2019_jmp]. From my review of the literature, I have \textit{apriori} expectations for the distribution of effects on my predictors in the form of a Laplace distribution which I explicitly define in my prior density function. I also have the additional benefit of having the ability to define its hyperparameters. Meaning I suspect that there is a peak around zero and that there are relatively large tails. This characterization of my prior fits with that of the Lasso - there are a large number of included predictors that have zero effect with a relatively smaller proportion of included predictors that do have an effect but are relatively unsure as to how large those coefficients might be. I can specify the scale of that uncertainty by specifying a hyperparameter for this LASSO prior. Without having to perform cross-validation as I would with the classical LASSO, my posterior distribution naturally reflects the uncertainty around the size of my L2 shrinkage parameter and can estimate models with different L2 shrinkage parameters simultaneously. As \verb|stan| includes implementations of this model, I rely on Hamiltonian Monte Carlo, a type of Markov Chain Monte Carlo sampling which allows for non-convexity in the L2 shrinkage parameters. As classical LASSO models are challenging to interpret due to cross-validation, using credible intervals offers a much less error-prone interpretation.

My measure of White Identity is ordinal. Though White Identity as a concept is likely continuous, through the specification of a cumulative density function with a logit link, my model bins this latent continuous space based on the number of response options. Though it creates a more complicated computational task, it is a more appropriate model specification given the available measure and my assumptions about the concept [@liddell_kruschke_2018_jesp].

To account for potential problems stemming from missing data, I impute my data by using multiple imputation with chained equations where the particular model I use is a random forest model to allow for more flexibility and to reduce model dependence [@buuren_goothuis-oudshoorn_2011, @marbach_2021]^[I impute 10 datasets and simultaneously fit my Bayesian LASSO on each dataset and pool the results. Uncertainty reflected in my reported credible intervals not only reflect the uncertainty from one model but my reported uncertainty also reflects the uncertainty generated from the imputation procedure. One drawback with this particular approach is that my normalized split-$\hat{R}$ will likely be greater than the widely recognized 1.01 cutoff that indicatess model convergence as a result of the pooling of my multiply imputed datasets.]. I report the results of the model fitted using listwise deletion in @tbl-2012-lasso-simple, @2016-lasso-simple, and @tbl-2020-lasso-simple.

@fig-2012-2016-2020-ordinal-lasso presents the estimates of my fitted ordinal models with the LASSO shrinkage prior^[@tbl-2012-2016-2020-ordinal-lasso presents the table of results.]. These models are fit on 6 chains with 2000 iterations each. To make the conclusion of whether a particular predictor "matters" for predicting White political identity, I examine the estimated credible intervals, which report the probability that the true estimate falls within the estimated range. I construct these credible intervals by reporting estimates between the 2.5% and 97.5% quantiles. This means that for a given credible interval, there is a 95% probability that the true value falls within that range. For values outside the range of the credible interval, it is relativelyu implausible that the given value is the true value. 

<!--
TODO:
  - Discussion of why these economic indicators versus others. Set up expectations about how/why these are different and what their effects on WID may be
  - Discussion of why these cultural/political indicators versus others. Set up expectations about how/why these are different and what their effects on WID may be 
  - Shorten discussion of penalized regression. Add details in footnotes and appendix
  - Footnote details about multiple imputation
  - Why include white influence and white discrimmination measures? Are they endogeneous?
  - Why include PID, what are my expectations and motivation for this and other control variables?
  - What does tradition breaking item represent?
-->

## Evidence from a penalized regression



## Results

<!--
TODO:
  - Group rows of results for figures and tables by economic and cultural/political attitudes
  - Cut discussion of priors about year to year differences
    - just do a post-hoc "isn't this interesting" interpretation and a discussion of what might be going on
  - Discuss a footnote on multicollinearity to make sure that economic nulls aren't due to being highly intercorrelated
-->

# Conclusion

<!--
TODO:
  - Make a strong assertion about my results
  - Discuss why I think economic factors don't matter when they matter in most identity papers
  - What does this mean for how we understand white identity? Elaborate on the takeaway of the paper and what I added but also what questions are still there.
-->

# Appendix

+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
|                                          | Abbreviated question                                       | ANES Coding                                                                                                                                                      | Author coding                                                                                                                                                             | Years            |
+==========================================+============================================================+==================================================================================================================================================================+===========================================================================================================================================================================+==================+
| White identity                           | How important is being White to your identity              | 1 = Extremely important; 2 = Very important; 3 = Moderately important; 4 = A little important; 5 = Not at all important; \<1 Missing, not asked, etc             | 1 = Not at all important; 2 = A little important; 3 = Moderately important; 4 = Very important; 5 = Extremely important; NA = Missing, not asked, etc                     | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| **Economics**                            |                                                            |                                                                                                                                                                  |                                                                                                                                                                           |                  |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Retrospective worse off                  | How much better worse off than 1 year ago                  | 1 = Much better; 2 = Somewhat better; 3 = The same; 4 = Somewhat worse; 5 = Much worse, \< 1 Missing, not asked, etc                                             | -2 = Much worse; -1 = Somewhat worse; 0 = The same; 1 = Somewhat better; 2 = Much better; NA = Missing, not asked, etc                                                    | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Economy worse                            | U.S. economy better worse off than 1 year ago              | 1 = Much better; 2 = somewhat better; 3 = Stayed about the same, 4 = Somewhat worse; 5 = Much worse; \< 1 Missing, not asked, etc                                | -2 = Much worse; -1 = Somewhat worse; 0 = The same; 1 = Somewhat better; 2 = Much better; NA = Missing, not asked, etc                                                    | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Unemployment worse                       | Unemployment better or worse than 1 year ago               | 1 = Much better; 2 = somewhat better; 3 = Stayed about the same, 4 = Somewhat worse; 5 = Much worse; \< 1 Missing, not asked, etc                                | -2 = Much worse; -1 = Somewhat worse; 0 = The same; 1 = Somewhat better; 2 = Much better; NA = Missing, not asked, etc                                                    | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Education                                | Educational attainment                                     | 1 = \< than High school; 2 = High school; 3 = Some post-High school; 4 = Bachelor's degree; \< 1 Missing, not asked, etc                                         | 1 = \< than High school; 2 = High school; 3 = Some post-High school; 4 = Bachelor's degree; NA = Missing, not asked, etc                                                  | 2012, 2020       |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Education (2016)                         | Educational attainment                                     | See ANES codebook                                                                                                                                                | See ANES codebook; NA = MIssing, not asked, etc                                                                                                                           | 2016             |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Worried about losing job                 | How worried about losing job in near future                | 1 = Not at all; 2 = A little; 3 = Moderately; 4 = Very; 5 = Extremely; \< 1 Missing, not asked, etc                                                              | -2 = Not at all; -1 = A little; 0 = Moderately; 1 = Very; 2 = Extremely                                                                                                   | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Immigrants take jobs                     | How likely immigration will take away jobs                 | 1 = Extremely; 2 = Very; 3 = Somewhat; 4 = Not at all; \< 1 Missing, not asked, etc                                                                              | 1 = Not at all; 2 = Somewhat; 3 = Very; 4 = Extremely; NA = Missing, not asked, etc                                                                                       | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Worried about family finances            | Worry about family financial situation                     | 1 = Extremely; 2 = Very; 3 = Moderately; 4 = A little; 5 = Not at all; \< 1 Missing, not asked, etc                                                              | 1 = Not at all, 2 = A little; 3 = Moderately; 4 = Very; 5 = Extremely; NA = Missing, not asked, etc                                                                       | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Know someone lost job                    | Know someone who lost job                                  | 1 = Someone lost job; 2 = No one lost job; \< 1 Missing, not asked, etc                                                                                          | 0 = No one lost job; 1 = Someone lost job; NA = Missing, not asked, etc                                                                                                   | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| **Political**                            |                                                            |                                                                                                                                                                  |                                                                                                                                                                           |                  |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| New lifestyles breaking society          | Newer lifestyles breaking down society                     | 1 = Agree strongly; 2 = Agree somewhat; 3 = Neither; 4 = Disagree somewhat; 5 = Disagree strongly; \< 1 Missing, not asked, etc                                  | -2 = Disagree strongly; -1 = Disagree somewhat; 0 = Neither, 1 = Agree somewhat; 2 = Agree strongly                                                                       | 2012, 2016       |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Government biased against Whites         | Does the Administration favor Blacks or Whites (2012 only) | 1 = Favors Whites; 2 = Favors Blacks; 3 = Treats both the same; \< 1 Missing, not asked, etc                                                                     | -1 = Favors Whites; 0 = Treats both the same; 1 = Favors Blacks; NA = Missing, not asked, etc                                                                             | 2012, 2016, 2020 |
|                                          |                                                            |                                                                                                                                                                  |                                                                                                                                                                           |                  |
|                                          | Does the Federal Gov treat Blacks or Whites Better         |                                                                                                                                                                  |                                                                                                                                                                           |                  |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Whites influence politics                | How much influence do Whites have on U.S. politics         | 1 = Too much; 2 = Just about right; 3 = Too little; \< 1 Missing, not asked, etc                                                                                 | -1 = Too little; 0 = Just about right; 1 = Too much; NA = Missing, not asked, etc                                                                                         | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Whites are discriminated against         | Discrimination in U.S. against Whites                      | 1 = A great deal; 2 = A lot; 3 = A moderate amount; 4 = A little; 5 = None at all; \< 1 Missing, not asked, etc                                                  | 1 = None at all; 2 = A little; 3 = A moderate amount; 4 = A lot; 5 = A great deal; NA = Missing, not asked, etc                                                           | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| **Controls**                             |                                                            |                                                                                                                                                                  |                                                                                                                                                                           |                  |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Racial Resentment                        | Standard, 4-item, battery                                  | 5-point Likert scale                                                                                                                                             | Avg of four questions; NA = Missing, not asked, etc                                                                                                                       | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Party ID                                 | Standard battery                                           | 1 = Strong Democrat; 2 = Democrat; 3 = Leans Democrat; 4 = Independent; 5 = Leans Republican; 6 = Republican; 7 = Strong Republican; \< 1 Missing, not asked, etc| 1 = Strong Democrat; 2 = Democrat; 3 = Leans Democrat; 4 = Independent/Neither; 5 = Leans Republican; 6 = Republican; 7 = Strong Republican; \< 1 Missing, not asked, etc | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Female                                   | Sex of respondent                                          | 1 = Male, 2 = Female; \< 1 Missing, not asked, etc                                                                                                               | 0 = Male, 1 = Female; NA = Missing, not asked, etc                                                                                                                        | 2012, 2016, 2020 |
+------------------------------------------+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
: ANES Measures {#tbl-anes-measures}